apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-convogent-demo-prod
  namespace: default
  annotations:
    kargo.akuity.io/authorized-stage: kargo-convogent-demo:convogent-demo-prod
spec:
  project: default
  source:
    repoURL: https://github.com/shilash-aivar/kargo-gitops.git
    targetRevision: main
    path: charts/kargo-demo
    helm:
      valueFiles:
      - ../../env/convogent-like-prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-convogent-demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
