apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: docker.io/18bit048/kargo-repo
      semverConstraint: ">=0.1.0"
      discoveryLimit: 5
