replicaCount: 1

image:
  repository: ghcr.io/your-org/kargo-demo
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  APP_ENV: dev
  APP_VERSION: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  host: kargo-demo.example.com

resources: {}

rollout:
  enabled: false
  strategy: canary  # canary | blueGreen
