apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: docker.io/18bit048/kargo-repo
  username: YOUR_DOCKERHUB_USERNAME
  password: YOUR_DOCKERHUB_TOKEN
