apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/18bit048/kargo-gitops.git
  username: YOUR_GITHUB_USERNAME
  password: YOUR_GITHUB_TOKEN
