image:
  repository: 18bit048/kargo-repo
  tag: 1.0.3

env:
  APP_ENV: dev
  APP_VERSION: latest

replicaCount: 1

ingress:
  enabled: false
  # host: kargo-demo-dev.example.com

# rollout:
#   enabled: true
#   strategy: canary
