image:
  repository: 18bit048/kargo-repo
  tag: "latest"  # Kargo updates this

env:
  APP_ENV: dev
  APP_VERSION: latest

replicaCount: 1

ingress:
  enabled: true
  host: kargo-demo-dev.example.com
