image:
  repository: 18bit048/kargo-repo
  tag: dfba18ce01a6ff0ebe7fe8edb5f8b04bb4953c32

env:
  APP_ENV: convogent-like-dev
  APP_VERSION: latest

replicaCount: 1

ingress:
  enabled: false
  # host: kargo-demo-dev.example.com

# rollout:
#   enabled: true
#   strategy: canary
