apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-convogent-demo-dev
  namespace: kargo-convogent-demo
spec:
  subscriptions:
  - image:
      repoURL: docker.io/18bit048/kargo-repo-dev
      allowTags: "^[0-9a-f]{7,40}$"
      imageSelectionStrategy: NewestBuild
      discoveryLimit: 5
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-convogent-demo-state
  namespace: kargo-convogent-demo
spec:
  subscriptions:
  - image:
      repoURL: docker.io/18bit048/kargo-repo-state
      allowTags: "^[0-9a-f]{7,40}$"
      imageSelectionStrategy: NewestBuild
      discoveryLimit: 5
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-convogent-demo-prod
  namespace: kargo-convogent-demo
spec:
  subscriptions:
  - image:
      repoURL: docker.io/18bit048/kargo-repo-prod
      allowTags: "^[0-9a-f]{7,40}$"
      imageSelectionStrategy: NewestBuild
      discoveryLimit: 5
